Repository hobbytrip/hobbytrip, pull requests merged in 2024-06, with the labels that each got.

#99 refactor: DM, Server 알림 기능 리팩토링
  src/backend/notification-service/.gitignore
  src/backend/notification-service/Dockerfile
  src/backend/notification-service/build.gradle
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/NotificationServiceApplication.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/dm/controller/DmNotificationController.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/dm/controller/TestController.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/dm/repository/NotificationRepository.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/dm/service/DmNotificationService.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/server/controller/ServerNotificationController.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/server/repository/ServerNotificationRepository.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/server/service/EmitterServerNotificationService.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/JasyptConfig.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/KafkaProducer.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/KafkaTopicConfig.java
  src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/ServerNotificationConsumerConfig.java
  src/backend/notification-service/src/test/java/com/capstone/notificationservice/DmNotificationServiceApplicationTests.java
  src/backend/notification-service/src/test/java/com/capstone/notificationservice/controller/DmDmNotificationControllerTest.java
Labels: pr, BE, feat, 우선순위: 중, env, refactor

#100 feat: 토큰 인증 확인 및 포럼 생성 기능 구현
  src/frontend/src/App.jsx
  src/frontend/src/actions/useAuthStore.js
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.module.css
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/Modal/ServerModal/CreateServer/CreateServer.jsx
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/hooks/User/login.js
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.module.css
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/utils/API/TEST_API.js
  src/frontend/src/utils/axiosInstance.js
  src/frontend/src/utils/instance.js
Labels: pr, feat, FE, refactor

#101 fix: 채팅 컴포넌트 버그 수정
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/utils/API/API.js
Labels: bug, FE

#109 feat: 포럼 커뮤니티 이벤트 구현
  src/frontend/public/image/emptyCon.jpg
  src/frontend/src/assets/image/emptyCon.jpg
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.module.css
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.jsx
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.module.css
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.module.css
  src/frontend/src/utils/API/TEST_API.js
  src/frontend/src/utils/axiosInstance.js
Labels: pr, feat, FE

#110 fix: 서버 수정, 링크 접속 버그 해결
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.module.css
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.module.css
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.jsx
  src/frontend/src/utils/axiosInstance.js
Labels: pr, FE

#111 fix: 채팅 기록 조회 안되는 버그
  src/frontend/src/App.jsx
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/Common/ChatRoom/FileUpload.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.module.css
  src/frontend/src/components/Modal/ForumModal/ForumType/ForumType.jsx
  src/frontend/src/components/Modal/ForumModal/ForumType/ForumType.module.css
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/LoginView/LoginView.module.css
  src/frontend/src/pages/RegView/RegView.module.css
Labels: bug, pr, FE

#114 fix: 미디어 연결 버그 수정 완료
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/utils/API/API.js
Labels: pr, FE

#116 refactor: 채팅방 구독
  src/frontend/src/actions/useChatStore.js
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
  src/frontend/src/pages/MainView/MainView.jsx
Labels: bug, pr, FE

#117 refactor: 웹소켓 연결 및 채팅방 구독 로직 리팩터링
  src/frontend/src/App.jsx
  src/frontend/src/actions/useChatStore.js
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/Common/ChatRoom/FileUpload.jsx
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.jsx
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/hooks/User/login.js
  src/frontend/src/hooks/useChat.js
  src/frontend/src/hooks/useServerData.js
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/CommunityChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/UserProfileView/UserProfileView.jsx
  src/frontend/src/utils/API/API.js
  src/frontend/src/utils/API/TEST_API.js
  src/frontend/src/utils/axiosInstance.js
  src/frontend/src/utils/instance.js
Labels: pr, feat, FE

#127 feat: 기존 프로젝트 설정정보 제거 & 서브모듈 설정정보 사용
  src/backend/notification-service/build.gradle
Labels: BE

#129 feat: SSE 연결 구현
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/image/no-friendCon.jpg
  src/frontend/src/App.jsx
  src/frontend/src/actions/useNotificationStore.js
  src/frontend/src/actions/useSSEStore.js
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/MainView/MyFriend/MyFriend.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.module.css
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/utils/API/API.js
  src/frontend/sw.js
Labels: feat, FE

#130 feat: 포럼 채널, 포럼 채팅 기능 구현
  src/frontend/src/actions/useForumListStore.js
  src/frontend/src/actions/useForumStore.js
  src/frontend/src/assets/image/forumLion.jpg
  src/frontend/src/components/Common/ChatRoom/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Common/ChatRoom/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ForumModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ForumModal/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.module.css
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.jsx
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.module.css
  src/frontend/src/components/Modal/ForumModal/ForumThumb/ForumThumb.jsx
  src/frontend/src/components/Modal/ForumModal/ForumThumb/ForumThumb.module.css
  src/frontend/src/components/Modal/ForumModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ForumModal/MessageSender/MessageSender.module.css
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/hooks/User/login.js
  src/frontend/src/hooks/useCategoryName.js
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
  src/frontend/src/pages/Chat/ChatRoom/CommunityChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/utils/API/API.js
Labels: pr, feat, FE

#131 feat: 포럼 업데이트 이벤트 추가
  src/frontend/src/App.jsx
  src/frontend/src/actions/useForumListStore.js
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.jsx
  src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.module.css
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
Labels: pr, feat, FE

#132 fix: 유저 친구 수정
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/WaitingFriendListResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
Labels: pr, BE

#140 bug: 친구 요청 및 수락 거절 이슈
  src/frontend/src/components/Modal/FriendModal/AddFriend/AddFriend.module.css
  src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
  src/frontend/src/components/Modal/FriendModal/MyFriend/MyFriend.jsx
  src/frontend/src/utils/API/API.js
Labels: bug, pr, FE

#141 refactor: 서비스 워커 삭제 및 SSE 연결 수정
  src/frontend/src/App.jsx
  src/frontend/src/actions/useSSEStore.js
  src/frontend/src/components/Common/ChatRoom/CommunityChatHeader/ChatHeader.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/sw.js
Labels: pr, FE, refactor

#142 feat: 서버 유저 목록 뷰 구현
  src/frontend/src/App.jsx
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.module.css
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/pages/ServerView/FriendsView/FriendsView.jsx
  src/frontend/src/pages/ServerView/FriendsView/FriendsView.module.css
  src/frontend/src/utils/API/API.js
Labels: pr, feat, FE

#143 feat: 유저 온오프라인 구현
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/actions/useUserStatusStore.js
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.module.css
  src/frontend/src/hooks/useSocketByServer.js
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
  src/frontend/src/pages/Chat/ChatRoom/CommunityChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.jsx
Labels: pr, feat, FE

#144 feat: 메뉴 뷰 기능 구현
  src/frontend/src/components/MenuView/ExitHeader/ExitHeader.jsx
  src/frontend/src/components/MenuView/Menu/Menu.jsx
  src/frontend/src/components/MenuView/Menu/Menu.module.css
  src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
  src/frontend/src/utils/API/API.js
Labels: pr, feat, FE

#145 feat: 친구 대기 요청 유/무 기능 추가
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/controller/FriendshipController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
Labels: pr, BE, feat

#155 feat: main 데탑 구현
  src/frontend/src/actions/useDmHistoryStore.js
  src/frontend/src/actions/usePlantesStore.js
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/MainView/MainHeader/MainHeader.jsx
  src/frontend/src/components/MainView/MainHeader/MainHeader.module.css
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.module.css
  src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
  src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.module.css
  src/frontend/src/components/Modal/FriendModal/MyFriend/MyFriend.module.css
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/TYPE/DM/DM.jsx
  src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.jsx
  src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.module.css
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/index.css
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/MainView/MainView.module.css
  src/frontend/src/pages/MediaView/MediaView.jsx
  src/frontend/src/pages/MediaView/MediaView.module.css
Labels: pr, feat, FE

#160 feat; DM 방 중복 업데이트 버그 해결
  src/frontend/src/actions/useDmHistoryStore.js
  src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.jsx
  src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.module.css
  src/frontend/src/components/TYPE/DM/DM.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
Labels: bug, pr, FE

#161 fix: 서버 join 버그 해결
  src/frontend/src/actions/usePlantesStore.js
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/Modal/FriendModal/MyFriend/MyFriend.module.css
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.jsx
  src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.module.css
  src/frontend/src/components/TYPE/Community/Server.jsx
  src/frontend/src/components/TYPE/Community/Server.module.css
  src/frontend/src/components/TYPE/DM/DM.jsx
  src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.jsx
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/MainView/MainView.module.css
Labels: pr, FE

#163 feat: 유저서비스 수정 및 리팩터링 사항
  src/frontend/src/App.jsx
  src/frontend/src/actions/useAuthStore.js
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/components/Common/ChatRoom/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Common/ChatRoom/ChatRoom.module.css
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/MenuView/Menu/Menu.jsx
  src/frontend/src/components/Modal/ForumModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
  src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
  src/frontend/src/components/Modal/FriendModal/FriendList/WaitingFriends.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
  src/frontend/src/components/ProfileCard/ProfileCard.jsx
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/components/ServerView/CategoryList/Channel/Channel.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.jsx
  src/frontend/src/components/TYPE/Community/CategoryList/Channel/Channel.jsx
  src/frontend/src/components/TYPE/Community/CommunityChatRoom.jsx
  src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.jsx
  src/frontend/src/components/TYPE/DM/DmChatRoom.jsx
  src/frontend/src/hooks/User/logout.js
  src/frontend/src/pages/Chat/ChatRoom/CommunityChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/DmChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/UserProfileView/UserProfileView.jsx
  src/frontend/src/utils/API/API.js
  src/frontend/src/utils/Auth/login.js
  src/frontend/src/utils/Auth/logout.js
  src/frontend/src/utils/Auth/reissueToken.js
  src/frontend/src/utils/User/getUser.js
  src/frontend/src/utils/axiosInstance.js
Labels: bug, pr, FE, refactor

#164 refactor: userID update
  src/frontend/src/components/TYPE/DM/DM.jsx
  src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.jsx
Labels: pr, feat, FE

#165 fix: PR 충돌 해결 과정에서 생긴 에러 수정
  src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
  src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
Labels: pr, FE

#181 fix: 서버 정보 조회 후 store 정보 업데이트 안되는 오류 해결
  src/frontend/src/actions/useChatStore.js
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/Common/ChatRoom/ChatRoom.module.css
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/components/TYPE/Community/CommunityChatRoom.jsx
  src/frontend/src/components/TYPE/Community/Server.jsx
  src/frontend/src/hooks/useFetchServer.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/utils/User/getUser.js
  src/frontend/src/utils/axiosInstance.js
Labels: bug, pr, FE

#183 Refactor: 미디어 데탑 뷰 수정
  src/frontend/src/components/Common/ChatRoom/CommunityChatHeader/ChatHeader.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.module.css
  src/frontend/src/components/MediaView/VideoComponent.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.module.css
  src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.jsx
  src/frontend/src/components/TYPE/Community/Server.jsx
  src/frontend/src/hooks/useChannelDatas.js
  src/frontend/src/hooks/useSSE.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/MediaView/MediaView.module.css
Labels: pr, FE

#192 fix: useSeverStore 관련 오류 해결
  src/frontend/src/actions/usePlantesStore.js
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/Common/ChatRoom/CommunityChatHeader/ChatHeader.jsx
  src/frontend/src/components/MainView/MainHeader/MainHeader.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/Modal/ServerModal/Channel/ChannelSetting/ChannelSetting.jsx
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.module.css
  src/frontend/src/components/Modal/ServerModal/Servers/InviteServer/InviteServer.jsx
  src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/FriendsList/FriendsList.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.jsx
  src/frontend/src/components/TYPE/Community/CommunityChatRoom.jsx
  src/frontend/src/components/TYPE/Community/Server.jsx
  src/frontend/src/components/TYPE/DM/DM.jsx
  src/frontend/src/hooks/useChannelDatas.js
  src/frontend/src/hooks/useFetchServer.js
Labels: bug, pr, FE
