Repository hobbytrip/hobbytrip, pull requests merged in 2024-05, with the labels that each got.

#42 refactor: 채팅 서비스 코드 리팩터링, fix: 채팅 조회시 삭제된 댓글 개수 버그 해결
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/DirectMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/repository/DirectMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/command/DirectMessageCommandService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/command/impl/DirectMessageCommandServiceImpl.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/query/DirectMessageQueryService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/query/impl/DirectMessageQueryServiceImpl.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/EmojiDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/ForumMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/repository/ForumMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/service/command/ForumMessageCommandService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/service/command/impl/ForumMessageCommandServiceImpl.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/service/query/ForumMessageQueryService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/service/query/impl/ForumMessageQueryServiceImpl.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/ServerMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/repository/ServerMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/command/ServerMessageCommandService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/command/impl/ServerMessageCommandServiceImpl.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/query/ServerMessageQueryService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/query/impl/ServerMessageQueryServiceImpl.java
Labels: bug, pr, BE, refactor

#43 feat: 유저 기능 구현
  src/frontend/dump.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/image/default-logo.png
  src/frontend/public/image/logo.png
  src/frontend/src/App.jsx
  src/frontend/src/actions/useAuthStore.js
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/assets/image/check-fill-gray.svg
  src/frontend/src/assets/image/check-fill.svg
  src/frontend/src/assets/image/default-logo.png
  src/frontend/src/assets/image/logo.png
  src/frontend/src/assets/image/symbols_check.svg
  src/frontend/src/components/DefaultIcon/DefaultIcon.jsx
  src/frontend/src/components/DefaultIcon/DefaultIcon.module.css
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/components/LoginForm/LoginForm.module.css
  src/frontend/src/components/NotificationBox/NotificationBox.jsx
  src/frontend/src/components/NotificationBox/NotificationBox.module.css
  src/frontend/src/components/ProfileCard/ProfileCard.jsx
  src/frontend/src/components/ProfileCard/ProfileCard.module.css
  src/frontend/src/components/RegForm/RegForm.jsx
  src/frontend/src/components/RegForm/RegForm.module.css
  src/frontend/src/components/StartView/StartView.jsx
  src/frontend/src/components/StartView/StartView.module.css
  src/frontend/src/index.css
  src/frontend/src/pages/LoginView/LoginView.module.css
  src/frontend/src/pages/LoginView/Loginview.jsx
  src/frontend/src/pages/RegView/RegView.jsx
  src/frontend/src/pages/RegView/RegView.module.css
  src/frontend/src/pages/UserProfileView/UserProfileView.jsx
  src/frontend/src/pages/UserProfileView/UserProfileView.module.css
  src/frontend/src/utils/instance.js
Labels: pr, feat, FE

#48 feat: MainView 구현
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/environment.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.jsx
  src/frontend/src/assets/image/logo.png
  src/frontend/src/components/MainView/MainHeader/MainHeader.jsx
  src/frontend/src/components/MainView/MainHeader/MainHeader.module.css
  src/frontend/src/components/MainView/MyFriend/MyFriend.jsx
  src/frontend/src/components/MainView/MyFriend/MyFriend.module.css
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/index.css
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/MainView/MainView.module.css
Labels: pr, feat, FE

#49 feat: MenuView 구현
  src/frontend/src/App.jsx
  src/frontend/src/components/MenuView/ExitHeader/ExitHeader.jsx
  src/frontend/src/components/MenuView/ExitHeader/ExitHeader.module.css
  src/frontend/src/components/MenuView/Menu/Menu.jsx
  src/frontend/src/components/MenuView/Menu/Menu.module.css
  src/frontend/src/pages/MenuView/MenuView.jsx
  src/frontend/src/pages/MenuView/MenuView.module.css
Labels: pr, feat, FE

#54 refactor: 사용자 정보 조회 함수 추가 및 코드 리팩토링
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/pages/UserProfileView/UserProfileView.jsx
Labels: pr, FE

#55 feat: 유저 친구 CRUD 구현
  src/backend/user-service/build.gradle
  src/backend/user-service/src/main/java/com/capstone/userservice/UserServiceApplication.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/controller/FriendshipController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/FriendStatusDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/FriendsStatusResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/FriendshipResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/WaitingFriendListResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/entity/Friendship.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/entity/FriendshipStatus.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/exception/FriendException.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/repository/FriendshipRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendsStatusClient.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/ProfileService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/AuthController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/UserController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/request/TokenRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/request/UserDeleteRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/request/UserRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/response/UserResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/entity/User.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/AuthService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/UserService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/dto/kafka/FriendReadResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/entity/RefreshToken.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/config/RedisConfig.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/respository/RefreshTokenRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/util/TokenUtil.java
Labels: pr, BE, feat, env

#62 refactor: 토큰 관리 방식 리팩토링
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/actions/useAuthStore.js
  src/frontend/src/components/LoginForm/LoginForm.jsx
  src/frontend/src/hooks/User/login.js
  src/frontend/src/hooks/User/logout.js
  src/frontend/src/utils/instance.js
Labels: pr, FE, refactor

#66 feat: 실시간 온/오프 상태 처리 기능, 커뮤니티 이벤트, 온/오프 이벤트 브로드캐스팅 구현
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/contorller/EmojiController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageCommandController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageQueryController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/CorsConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/OpenFeignConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/StompConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaTopicConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/community/CategoryEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/community/ChannelEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/community/DmEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/community/ForumEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/community/ServerEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/state/ConnectionStateEventConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/client/CommunityServiceClient.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/client/StateServiceClient.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/client/UserServerDmInfo.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/CategoryEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/ChannelEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/DmEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/ForumEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/ServerEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/ChannelType.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/CommunityCategoryEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/CommunityChannelEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/CommunityDmEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/CommunityForumEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/CommunityServerEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/community/dto/FileResponseDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/state/connectionStateEventConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/state/dto/ConnectionStateEventResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/producer/KafkaProducer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/producer/dto/ConnectionStateEventDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/producer/dto/ConnectionStateInfo.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/websocket/WebSocketConnectionHandler.java
Labels: pr, BE, feat

#67 feat: 영상, 음성 컴포넌트 연결 및 구현
  src/frontend/package.json
  src/frontend/src/App.jsx
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/assets/image/logo.png
  src/frontend/src/assets/image/main/menu_icon.png
  src/frontend/src/assets/image/main/search_icon.png
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.module.css
  src/frontend/src/components/MediaView/UserVideoComponent.jsx
  src/frontend/src/components/MediaView/VideoComponent/VideoComponent.jsx
  src/frontend/src/components/MediaView/VideoComponent/VideoComponent.module.css
  src/frontend/src/pages/MediaView/MediaView.jsx
  src/frontend/src/pages/MediaView/MediaView.module.css
Labels: pr, FE

#68 refactor: 전체 url 수정 및 isLogin 수정
  src/backend/user-service/build.gradle
  src/backend/user-service/src/main/java/com/capstone/userservice/UserServiceApplication.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/FriendStatusDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/FriendReadResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/AuthController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/UserController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/AuthService.java
  src/backend/user-service/src/test/java/com/capstone/userservice/UserServiceApplicationTests.java
  src/backend/user-service/src/test/resources/payload/settlement-response.json
Labels: pr, BE, refactor

#69 feat: 미디어 api 수정
  src/frontend/public/image/logo-white.png
  src/frontend/src/assets/image/main/menu_icon.png
  src/frontend/src/assets/image/main/search_icon.png
  src/frontend/src/components/MainView/MainHeader/MainHeader.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/MediaView/MediaCall/MediaCall.module.css
  src/frontend/src/components/MediaView/UserVideoComponent.jsx
  src/frontend/src/components/MediaView/VideoComponent.jsx
  src/frontend/src/components/MediaView/VideoComponent/VideoComponent.module.css
Labels: pr, FE

#70 feat: 커뮤니티 채팅 구현
  src/frontend/index.html
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/public/image/serverIcons/server_planet_icon1.png
  src/frontend/public/image/serverIcons/server_planet_icon2.png
  src/frontend/public/image/serverIcons/server_planet_icon3.png
  src/frontend/public/image/serverIcons/server_planet_icon4.png
  src/frontend/src/App.jsx
  src/frontend/src/actions/useUserStore.js
  src/frontend/src/assets/image/logo-white.png
  src/frontend/src/assets/image/serverIcons/server_planet_icon1.png
  src/frontend/src/assets/image/serverIcons/server_planet_icon2.png
  src/frontend/src/assets/image/serverIcons/server_planet_icon3.png
  src/frontend/src/assets/image/serverIcons/server_planet_icon4.png
  src/frontend/src/components/Common/ChatRoom/CommunityChatHeader/ChatHeader.jsx
  src/frontend/src/components/Common/ChatRoom/CommunityChatHeader/ChatHeader.module.css
  src/frontend/src/components/Modal/ChatModal/ChatChannelInfo/ChatChannelInfo.jsx
  src/frontend/src/components/Modal/ChatModal/ChatChannelInfo/ChatChannelInfo.module.css
  src/frontend/src/components/Modal/ChatModal/ChatHeaderModal/ChatHeader.module.css
  src/frontend/src/components/Modal/ChatModal/ChatHeaderModal/ChatHeaderModal.jsx
  src/frontend/src/components/Modal/ChatModal/ChatSearchBar/ChatSearchBar.jsx
  src/frontend/src/components/Modal/ChatModal/ChatSearchBar/ChatSearchBar.module.css
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/CreateChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/CreateChatModal.module.css
  src/frontend/src/components/Modal/ServerModal/CreateServer/CreateServer.jsx
  src/frontend/src/hooks/useFormatDate.js
  src/frontend/src/hooks/usePlanetIcon.js
  src/frontend/src/main.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
Labels: pr, feat, FE

#79 feat: 채팅 컴포넌트 리팩토링
  src/frontend/src/App.jsx
  src/frontend/src/components/Common/ChatRoom/InfiniteScrollComponent.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/CreateChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/CreateChatModal.module.css
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/FileUpload.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.module.css
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
Labels: pr, feat, FE

#84 feat: 채팅 메세지 수정,삭제 기능 구현 및 리팩토링
  src/frontend/src/App.jsx
  src/frontend/src/actions/useWebSocketStore.js
  src/frontend/src/components/Modal/ChatModal/ChatChannelType/ChatChannelType.jsx
  src/frontend/src/components/Modal/ChatModal/ChatChannelType/ChatChannelType.module.css
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.module.css
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.module.css
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/CreateChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
Labels: pr, feat, FE

#88 feat: 서버 관련 기능 구현
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.jsx
  src/frontend/src/actions/useNotificationStore.js
  src/frontend/src/actions/useServerStore.js
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
  src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
  src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.module.css
  src/frontend/src/components/Modal/ServerModal/CreateChannel.jsx/CreateChannel.jsx
  src/frontend/src/components/Modal/ServerModal/CreateChannel.jsx/CreateChannel.module.css
  src/frontend/src/components/Modal/ServerModal/CreateServer/CreateServer.jsx
  src/frontend/src/components/Modal/ServerModal/CreateServer/CreateServer.module.css
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.module.css
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
  src/frontend/src/components/ServerView/SeverSetting/ServerSetting.module.css
  src/frontend/src/hooks/useServerData.js
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.jsx
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.module.css
  src/frontend/src/pages/ServerView/SettingView/SettingView.jsx
  src/frontend/src/pages/ServerView/SettingView/SettingView.module.css
Labels: pr, FE

#87 유저입장시 상태관리서버에 유저위치전송
  src/backend/sig-service/Dockerfile
  src/backend/sig-service/build.gradle
  src/backend/sig-service/src/main/java/capstone/sigservice/Kafka/KafkaProducer.java
  src/backend/sig-service/src/main/java/capstone/sigservice/SigServiceApplication.java
  src/backend/sig-service/src/main/java/capstone/sigservice/config/JasyptConfig.java
  src/backend/sig-service/src/main/java/capstone/sigservice/config/KafkaProducerConfig.java
  src/backend/sig-service/src/main/java/capstone/sigservice/config/KafkaTopicConfig.java
  src/backend/sig-service/src/main/java/capstone/sigservice/config/WebMvcConfig.java
  src/backend/sig-service/src/main/java/capstone/sigservice/controller/CommunitySessionController.java
  src/backend/sig-service/src/main/java/capstone/sigservice/dto/UserLocationEventDto.java
  src/backend/sig-service/src/main/java/capstone/sigservice/service/CommunitySessionService.java
  src/backend/sig-service/src/test/java/capstone/sigservice/SigServiceApplicationTests.java
Labels: pr, BE, feat

#90 refactor: 유저 온/오프라인 상태 확인 및 JWT 검증 없는 API 추가
  src/backend/user-service/.gitignore
  src/backend/user-service/build.gradle
  src/backend/user-service/src/main/java/com/capstone/userservice/UserServiceApplication.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/controller/FriendshipController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/ConnectionState.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/FriendStatusDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/FriendReadResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/FriendsStatusResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/UserConnectionStateResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/repository/FriendshipRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendsStatusClient.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/controller/ProfileController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/ProfileService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/UserServiceClient.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/response/UserFeignResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/config/FeignConfig.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/config/JasyptConfig.java
Labels: pr, BE, feat, env, refactor

#91 feat: 카테고리 기능 구현
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CategorySetting/CategorySetting.module.css
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
  src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.module.css
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
  src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.module.css
  src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
  src/frontend/src/components/ServerView/CategoryList/CategoryList.module.css
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.jsx
  src/frontend/src/pages/ServerView/CategoryView/CategoryView.module.css
Labels: pr, FE

#96 refactor: 미디어 리팩토링
  src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
  src/frontend/src/pages/MainView/MainView.jsx
  src/frontend/src/utils/API/API.js
Labels: pr, FE, refactor

#97 feat: 포럼 채팅 기록 조회 기능
  src/frontend/src/App.jsx
  src/frontend/src/components/Common/ChatRoom/FileUpload.jsx
  src/frontend/src/components/Modal/ChatModal/ChatMessage/ChatMessage.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
  src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.module.css
  src/frontend/src/components/Modal/ForumModal/ForumType/ForumType.jsx
  src/frontend/src/components/Modal/ForumModal/ForumType/ForumType.module.css
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
  src/frontend/src/pages/Chat/ForumRoom/ForumRoom.module.css
Labels: enhancement, pr, FE
