Repository hobbytrip/hobbytrip, pull requests merged in 2024-04, with the labels that each got.

#10 [BE] 서비스 디스커버리 역할의 유레카 서버 구현
  src/backend/discovery-service/.gitignore
  src/backend/discovery-service/build.gradle
  src/backend/discovery-service/gradle/wrapper/gradle-wrapper.jar
  src/backend/discovery-service/gradle/wrapper/gradle-wrapper.properties
  src/backend/discovery-service/gradlew
  src/backend/discovery-service/gradlew.bat
  src/backend/discovery-service/settings.gradle
  src/backend/discovery-service/src/main/java/com/example/discoveryservice/DiscoveryServiceApplication.java
  src/backend/discovery-service/src/test/java/com/example/discoveryservice/DiscoveryServiceApplicationTests.java
Labels: pr, BE, feat, 우선순위: 하, env

#14 feat: 서버 채팅 CUD, 프로듀서, 컨슈머 구현
  src/backend/chat-service/.gitignore
  src/backend/chat-service/build.gradle
  src/backend/chat-service/gradle/wrapper/gradle-wrapper.jar
  src/backend/chat-service/gradle/wrapper/gradle-wrapper.properties
  src/backend/chat-service/gradlew
  src/backend/chat-service/gradlew.bat
  src/backend/chat-service/settings.gradle
  src/backend/chat-service/src/main/java/capstone/chatservice/ChatserviceApplication.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/model/AutoIncrementSequence.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/model/BaseModel.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/domain/ServerMessage.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/ServerMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/request/ServerMessageCreateRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/request/ServerMessageDeleteRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/request/ServerMessageModifyRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/response/ServerMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/repository/ServerMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/ServerMessageService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/StompConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaTopicConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/util/SequenceGenerator.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumerService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducerService.java
  src/backend/chat-service/src/test/java/capstone/chatservice/ChatserviceApplicationTests.java
Labels: pr, BE, feat

#23 feat: 서버 채팅, 댓글 조회 api와 이모지 생성, 삭제 api 구현
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/contorller/EmojiController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/domain/Emoji.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/EmojiDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/request/EmojiCreateRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/request/EmojiDeleteRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/repository/EmojiRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/service/EmojiService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/ServerMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/repository/ServerMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/ServerMessageService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/EmojiChatConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/ServerChatConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducer.java
Labels: pr, BE, feat

#25 [BE] 유저 서비스 프로젝트 초기 설정 및 기능 구현
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/environment.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/suggestion.yml
  src/backend/user-service/.gitignore
  src/backend/user-service/build.gradle
  src/backend/user-service/gradle/wrapper/gradle-wrapper.jar
  src/backend/user-service/gradle/wrapper/gradle-wrapper.properties
  src/backend/user-service/gradlew
  src/backend/user-service/gradlew.bat
  src/backend/user-service/settings.gradle
  src/backend/user-service/src/main/java/com/capstone/userservice/UserServiceApplication.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/AuthController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/TokenRequestDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserRequestDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserResponseDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/entity/Authority.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/entity/User.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/repository/UserRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/AuthService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/CustomUserDetailsService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/dto/DataResponseDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/dto/ErrorResponseDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/dto/ResponseDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/dto/TokenDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/filter/JwtFilter.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/config/JwtSecurityConfig.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/config/SecurityConfig.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/entity/RefreshToken.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/exception/Code.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/exception/GlobalException.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/exception/JwtAccessDeniedHandler.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/exception/JwtAuthenticationEntryPoint.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/respository/RefreshTokenRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/util/TokenUtil.java
  src/backend/user-service/src/test/java/com/capstone/userservice/UserServiceApplicationTests.java
Labels: pr, BE, feat, 우선순위: 하, env

#30 feat: DM CRUD api, DM producer, consumer 구현
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/domain/DirectMessage.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/DirectMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageCreateRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageDeleteRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageModifyRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/repository/DirectMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/DirectMessageService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/repository/EmojiRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/DirectChatConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducer.java
Labels: pr, BE, feat

#33 feat: 카테고리 CUD, DM 프로필 이미지, 채널 CUD, 카프카 설정
  src/backend/community-service/build.gradle
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/controller/CategoryCommandController.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryCreateRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryDeleteRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryResponseDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryUpdateRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/category/service/CategoryCommandService.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/controller/CategoryController.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/controller/ChannelCommandController.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelCreateRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelDeleteRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelResponseDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelUpdateRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/entity/Channel.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/service/ChannelCommandService.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/controller/DmCommandController.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmDeleteProfileRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmResponseDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmUpdateProfileRequestDto.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/entity/Dm.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/service/DmCommandService.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/server/controller/ServerCommandController.java
  src/backend/community-service/src/main/java/capstone/communityservice/domain/server/service/ServerCommandService.java
  src/backend/community-service/src/main/java/capstone/communityservice/global/config/KafkaProducerConfig.java
  src/backend/community-service/src/main/java/capstone/communityservice/global/config/KafkaTopicConfig.java
Labels: pr, BE, feat, env

#35 feat: 포럼 채팅 CRUD api 구현, 포럼 채팅 DTO producer, consumer 구현
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/repository/EmojiRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/controller/ForumMessageController.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/domain/ForumMessage.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/ForumMessageDto.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/request/ForumMessageCreateRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/request/ForumMessageDeleteRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/request/ForumMessageModifyRequest.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageCreateResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageDeleteResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/dto/response/ForumMessageModifyResponse.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/repository/ForumMessageRepository.java
  src/backend/chat-service/src/main/java/capstone/chatservice/domain/forum/service/ForumMessageService.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaTopicConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/ForumChatConsumerConfig.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/DirectChatConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/EmojiChatConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/ForumChatConsumer.java
  src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/consumer/ServerChatConsumer.java
Labels: pr, BE, feat

#36 feat: 유저 프로필 RU, 유저 D api 구현
  src/backend/user-service/build.gradle
  src/backend/user-service/src/main/java/com/capstone/userservice/UserServiceApplication.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/controller/ProfileController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/request/ProfileNicknameRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/request/ProfileNoticeRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/request/ProfileStatusMessageRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/response/ProfileNicknameResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/response/ProfileNoticeResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/response/ProfileResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/response/ProfileStatusMessageResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/exception/ProfileException.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/repository/ProfileRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/ProfileService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/AuthController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/UserController.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/TokenRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserDeleteRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserRequest.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserResponse.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserResponseDto.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/entity/User.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/exception/UserException.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/AuthService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/service/UserService.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/common/entity/RefreshToken.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/respository/RefreshTokenRepository.java
  src/backend/user-service/src/main/java/com/capstone/userservice/global/util/TokenUtil.java
Labels: pr, BE, feat
